version: 2

updates:
  - package-ecosystem: uv
    directory: /backend
    versioning-strategy: increase-if-necessary
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
      - /runner
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: klee/klee
      - dependency-name: node
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/London
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
