FROM kleeweb-worker

RUN apt-get update
RUN apt-get install -y sudo docker.io

WORKDIR /worker

RUN pip install flake8

CMD flake8 --extend-ignore=E722 --max-complexity 12 . \
  && python -m unittest discover -s ./worker/tests/ -p 'test_*.py'
