# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160808_1302'),
        ('frontend', '0003_task_worker_name'),
    ]

    operations = [
    ]
