# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_merge_20160816_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default=b'Guest', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(default=b'None', max_length=40),
        ),
    ]
