/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telemetry */
        get: operations["telemetry_admin_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HaltReason
         * @enum {string}
         */
        HaltReason: "completed" | "max_time" | "cancelled";
        /** Job */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** @default pending */
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            result?: components["schemas"]["JobResult"] | null;
            readonly outcome: components["schemas"]["JobOutcome"] | null;
        };
        /** JobCreated */
        JobCreated: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
        };
        /**
         * JobOutcome
         * @enum {string}
         */
        JobOutcome: "completed" | "max_time" | "cancelled" | "compile_error" | "failed";
        /** JobRequest */
        JobRequest: {
            /** Source */
            source: string;
            flags?: components["schemas"]["KleeFlags"];
        };
        /** JobResult */
        JobResult: {
            /** Test Cases */
            test_cases: components["schemas"]["TestCase"][];
            /** Messages */
            messages: string;
            /** Warnings */
            warnings: string;
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /**
             * Program Output
             * @default
             */
            program_output: string;
            /** Compile Error */
            compile_error?: string | null;
            halt_reason?: components["schemas"]["HaltReason"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "parsing" | "done" | "failed";
        /** KleeFlags */
        KleeFlags: {
            /**
             * Max Time
             * @default 60
             */
            max_time: number;
            /**
             * Max Memory
             * @default 512
             */
            max_memory: number;
            /** @default none */
            query_format: components["schemas"]["QueryFormat"];
            /**
             * Extra Flags
             * @default
             */
            extra_flags: string;
            sym_stdin?: components["schemas"]["SymStdin"] | null;
            sym_files?: components["schemas"]["SymFiles"] | null;
            sym_args?: components["schemas"]["SymArgs"] | null;
        };
        /**
         * QueryFormat
         * @enum {string}
         */
        QueryFormat: "none" | "kquery";
        /** QueueTelemetry */
        QueueTelemetry: {
            /** Name */
            name: string;
            /** Depth */
            depth: number;
        };
        /** SymArgs */
        SymArgs: {
            /** Count Min */
            count_min: number;
            /** Count Max */
            count_max: number;
            /** Length */
            length: number;
        };
        /** SymFiles */
        SymFiles: {
            /** Count */
            count: number;
            /** Size */
            size: number;
        };
        /** SymStdin */
        SymStdin: {
            /** Size */
            size: number;
        };
        /** SymbolicInput */
        SymbolicInput: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Bytes Hex */
            bytes_hex: string;
        };
        /** Telemetry */
        Telemetry: {
            /** Workers */
            workers: components["schemas"]["WorkerTelemetry"][];
            queue?: components["schemas"]["QueueTelemetry"] | null;
        };
        /** TestCase */
        TestCase: {
            /** Name */
            name: string;
            /** Inputs */
            inputs: components["schemas"]["SymbolicInput"][];
            /** Error */
            error?: string | null;
            /** Path Constraint */
            path_constraint?: string | null;
            /** Program Output */
            program_output?: string | null;
        };
        /** UsageStats */
        UsageStats: {
            /** Outcomes */
            outcomes: {
                [key: string]: number;
            };
            /** Cache Hits */
            cache_hits: number;
            /** Test Cases Generated */
            test_cases_generated: number;
            /** Instructions Executed */
            instructions_executed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerTelemetry */
        WorkerTelemetry: {
            /** Name */
            name: string;
            /** Concurrency */
            concurrency: number;
            /** Active */
            active: number;
            /** Reserved */
            reserved: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    telemetry_admin_telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Telemetry"];
                };
            };
        };
    };
    stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageStats"];
                };
            };
        };
    };
}
