---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - init
    - role: geerlingguy.pip
      pip_package: python3-pip
      timeout: 60
    # TODO: Move everything to python3. This is a dependency for Django
    - role: geerlingguy.pip
      pip_package: python-pip
      timeout: 60
    - geerlingguy.docker
    - common

# Configure and deploy message queue servers.
- hosts: redisservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - redis

# Configure and deploy message database servers.
- hosts: dbservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - db

# Configure and deploy the web servers.
- hosts: webservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - web

# Configure and deploy the worker nodes.
- hosts: workers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - worker
