- hosts: all
  user: vagrant
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common
    - redis
    - db
    - web
    - worker
    - webdriver
  vars_files:
    - vars/development.yml
