- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/development.yml
  roles:
    - init
    - role: geerlingguy.pip
      pip_package: python3-pip
      pip_executable: pip3
      timeout: 60
    # For now need to keep this in to be able to do task Docker pull Redis 3.2 
    # on the NON-FIRST run of vagrant provision
    - role: geerlingguy.pip
      pip_package: python-pip
      timeout: 60
    - geerlingguy.docker
    - common
    - redis
    - db
    - web
    - worker
    - webdriver
