---
- name: Install flake8
  pip: name=flake8

- name: Install HTTPIE
  pip: name=httpie

- name: "Install E2E test dependencies"
  shell: npm install --dev chdir={{ application_dir }}/tests
  become: no
